# Generated by Django 2.0.4 on 2018-04-17 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FaceChattr',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('charaValue', models.CharField(max_length=9999)),
            ],
        ),
    ]
