spring:
  datasource:
    url: jdbc:mysql://172.17.0.2/test
    username: root
    password: 123456
    test-while-idle: true
    validation-query: SELECT 1

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  http:
    multipart:
      max-file-size: 20Mb
      max-request-size: 20Mb

server:
  port: 8080